services:
  - type: web
    name: asif-analyzer
    env: python
    buildCommand: "pip install -U pip && pip install -r requirements.txt"
    startCommand: "gunicorn app:app"
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.8
